# Generated by Django 3.2.9 on 2022-03-18 13:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('billing_date', models.DateField(default=django.utils.timezone.now)),
                ('billing_address', models.CharField(blank=True, max_length=100)),
                ('extra1_name', models.CharField(blank=True, max_length=100)),
                ('extra1_cost', models.FloatField(blank=True, null=True)),
                ('extra2_name', models.CharField(blank=True, max_length=100)),
                ('extra2_cost', models.FloatField(blank=True, null=True)),
                ('total_cost', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=100)),
                ('cust_tel_no', models.CharField(max_length=12)),
                ('cust_email', models.CharField(max_length=100)),
                ('cust_budget_code', models.IntegerField()),
                ('cust_type', models.FloatField(choices=[(1.0, 'Normal'), (1.5, 'External')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_date', models.DateField(default=django.utils.timezone.now)),
                ('num_samples', models.IntegerField()),
                ('specimen_procedure', models.CharField(blank=True, max_length=500, verbose_name='Specimen/procedure')),
                ('chemical_fixation', models.CharField(blank=True, max_length=100, verbose_name='Chemical Fixation')),
                ('neg_staining', models.CharField(blank=True, max_length=100, verbose_name='Negative staining')),
                ('cryofixation', models.CharField(blank=True, max_length=100, verbose_name='Cryofixation')),
                ('tem_embedding_schedule', models.CharField(blank=True, max_length=100, verbose_name='TEM embedding schedule')),
                ('dehydration', models.CharField(blank=True, max_length=100, verbose_name='Dehydration')),
                ('resin', models.CharField(blank=True, max_length=100, verbose_name='Resin')),
                ('sem', models.CharField(blank=True, max_length=3, verbose_name='SEM')),
                ('sem_mount', models.CharField(blank=True, max_length=50, verbose_name='SEM Mount')),
                ('fd', models.CharField(blank=True, max_length=50, verbose_name='FD')),
                ('cpd', models.CharField(blank=True, max_length=50, verbose_name='CPD')),
                ('sem_cost', models.CharField(blank=True, max_length=50, verbose_name='SEM Cost')),
                ('temp_time', models.CharField(blank=True, max_length=50, verbose_name='Temp/Time')),
                ('immunolabelling', models.CharField(blank=True, max_length=100, verbose_name='Immunolabeling')),
                ('first_dilution_time', models.CharField(blank=True, max_length=100, verbose_name='1°Ab/dilution/time')),
                ('second_dilution_time', models.CharField(blank=True, max_length=100, verbose_name='2°Ab-gold/dilution/time')),
                ('contrast_staining', models.CharField(blank=True, max_length=100, verbose_name='Contrast staining')),
                ('comments_results', models.CharField(blank=True, max_length=500, verbose_name='Comments/Results')),
                ('status', models.IntegerField(choices=[(0, 'Prep'), (1, 'Section'), (2, 'Image'), (3, 'Bill')], default=0)),
                ('total', models.FloatField(default=0)),
                ('cust_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_system_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('normal_price', models.FloatField()),
                ('external_price', models.FloatField()),
                ('unit_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_name', models.CharField(max_length=100)),
                ('worker_tel_no', models.CharField(max_length=12)),
                ('worker_email', models.CharField(max_length=100)),
                ('cust_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_system_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProjectBridge',
            fields=[
                ('worker_project_bridge_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imaging_system_app.project')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imaging_system_app.worker')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectServicesBridge',
            fields=[
                ('project_services_bridge_id', models.AutoField(primary_key=True, serialize=False)),
                ('units', models.FloatField()),
                ('cost', models.FloatField(default=0)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_system_app.project')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imaging_system_app.services')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBillBridge',
            fields=[
                ('project_bill_bridge_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_system_app.bill')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imaging_system_app.project')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imaging_system_app.customer'),
        ),
    ]
