# Generated by Django 3.2.9 on 2021-11-24 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=100)),
                ('cust_tel_no', models.CharField(max_length=11)),
                ('cust_email', models.CharField(max_length=100)),
                ('cust_budget_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_name', models.CharField(max_length=100)),
                ('worker_tel_no', models.CharField(max_length=11)),
                ('worker_email', models.CharField(max_length=100)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imaging_system_app.customer')),
            ],
        ),
    ]
