# Generated by Django 3.2 on 2022-01-09 00:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_system_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('billind_date', models.DateField(default=django.utils.timezone.now)),
                ('billing_address', models.CharField(max_length=100)),
                ('total_cost', models.IntegerField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imaging_system_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_date', models.DateField(default=django.utils.timezone.now)),
                ('num_samples', models.IntegerField()),
                ('specimen_procedure', models.CharField(max_length=500)),
                ('chemical_fixation', models.CharField(max_length=100)),
                ('neg_staining', models.CharField(max_length=100)),
                ('cryofixation', models.CharField(max_length=100)),
                ('tem_embedding_schedule', models.CharField(max_length=100)),
                ('dehydration', models.CharField(max_length=100)),
                ('resin', models.CharField(max_length=100)),
                ('sem', models.CharField(max_length=3)),
                ('sem_mount', models.CharField(max_length=50)),
                ('fd', models.CharField(max_length=50)),
                ('cpd', models.CharField(max_length=50)),
                ('sem_cost', models.CharField(max_length=50)),
                ('temp_time', models.CharField(max_length=50)),
                ('immunolabelling', models.CharField(max_length=100)),
                ('first_dilution_time', models.CharField(max_length=100)),
                ('second_dilution_time', models.CharField(max_length=100)),
                ('contrast_staining', models.CharField(max_length=100)),
                ('comments_results', models.CharField(max_length=500)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imaging_system_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_type', models.CharField(max_length=100)),
                ('discount', models.FloatField()),
                ('jeol1200tem_cost', models.FloatField()),
                ('jeol100sem_cost', models.FloatField()),
                ('tem_processing_cost', models.FloatField()),
                ('sectioning_stained_cost', models.FloatField()),
                ('sectioning_contrast_stained_cost', models.FloatField()),
                ('negative_staining_cost', models.FloatField()),
                ('sem_processing_mounting_cost', models.FloatField()),
                ('sem_processing_fd_cost', models.FloatField()),
                ('sem_cost', models.FloatField()),
                ('immunolabelling_cost', models.FloatField()),
                ('cryosectioning_cost', models.FloatField()),
                ('freeze_fracture_cost', models.FloatField()),
                ('ir_white_cost', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='WorkerProjectBridge',
            fields=[
                ('worker_project_bridge_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imaging_system_app.project')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imaging_system_app.worker')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBillDetails',
            fields=[
                ('project_bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('jeol1200tem_unit', models.IntegerField()),
                ('jeol100sem_unit', models.IntegerField()),
                ('tem_processing_unit', models.IntegerField()),
                ('sectioning_stained_unit', models.IntegerField()),
                ('sectioning_contrast_stained_unit', models.IntegerField()),
                ('negative_staining_unit', models.IntegerField()),
                ('sem_processing_mounting_unit', models.IntegerField()),
                ('sem_processing_fd_unit', models.IntegerField()),
                ('sem_unit', models.IntegerField()),
                ('immunolabelling_unit', models.IntegerField()),
                ('cryosectioning_unit', models.IntegerField()),
                ('freeze_fracture_unit', models.IntegerField()),
                ('ir_white_unit', models.IntegerField()),
                ('extra1_name', models.CharField(max_length=100)),
                ('extra1_cost', models.FloatField()),
                ('extra2_name', models.CharField(max_length=100)),
                ('extra2_cost', models.FloatField()),
                ('extra3_name', models.CharField(max_length=100)),
                ('extra3_cost', models.FloatField()),
                ('total', models.FloatField()),
                ('project_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='imaging_system_app.project')),
            ],
            options={
                'verbose_name_plural': 'Project bill details',
            },
        ),
        migrations.CreateModel(
            name='ProjectBillBridge',
            fields=[
                ('project_bill_bridge_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imaging_system_app.bill')),
                ('project_bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imaging_system_app.projectbilldetails')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='service_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='imaging_system_app.services'),
        ),
    ]
