# Generated by Django 3.2 on 2022-02-10 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_system_app', '0002_alter_bill_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbillbridge',
            name='bill_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaging_system_app.bill'),
        ),
    ]
