# Generated by Django 3.2 on 2022-01-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_system_app', '0005_auto_20220109_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbilldetails',
            name='cryosectioning_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectbilldetails',
            name='extra1_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectbilldetails',
            name='extra2_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectbilldetails',
            name='extra3_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectbilldetails',
            name='freeze_fracture_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectbilldetails',
            name='immunolabelling_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectbilldetails',
            name='ir_white_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectbilldetails',
            name='jeol100sem_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectbilldetails',
            name='jeol1200tem_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectbilldetails',
            name='negative_staining_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectbilldetails',
            name='sectioning_contrast_stained_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectbilldetails',
            name='sectioning_stained_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectbilldetails',
            name='sem_processing_fd_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectbilldetails',
            name='sem_processing_mounting_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectbilldetails',
            name='sem_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectbilldetails',
            name='tem_processing_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
