# Generated by Django 3.2 on 2022-01-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_system_app', '0007_rename_billind_date_bill_billing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billing_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
