# Generated by Django 3.2 on 2022-01-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_system_app', '0008_alter_bill_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
