# Generated by Django 3.2.9 on 2022-01-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_system_app', '0010_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'Prep'), (1, 'Section'), (2, 'Image'), (3, 'Bill')], default=0),
        ),
    ]
